# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: summit_rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp=0.20.0
  - hisat2=2.1.0
  - picard=2.18.27
  - conda-forge::r-data.table=1.12.0
  - conda-forge::r-gplots=3.0.1.1
  - bioconductor-deseq2=1.22.1
  - conda-forge::r-markdown=0.9
  - samtools=1.9
  - deeptools=3.2.0
  - bedtools=2.28.0
  - htseq=0.11.2
